version: '3.5'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: AuthMeSuperSecurePassword123
      ACCEPT_EULA: "Y" # Add Persistence
    ports:
      - 1433:1433

  dotnet-worker:
    image: ${DOCKER_REGISTRY-}dotnet-worker
    build:
      context: ./src/dotnet
      dockerfile: ./AuthMe.Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - mssql