version: '3.5'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: AuthMeSuperSecurePassword123
      ACCEPT_EULA: "Y" # Add Persistence
    ports:
      - 1433:1433

  dotnet-worker:
    image: ${DOCKER_REGISTRY-}dotnet-worker
    build:
      context: ./src/dotnet
      dockerfile: ./AuthMe.Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - mssql
  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3307:3306
  
  spring-worker:
    image: ${DOCKER_REGISTRY-}spring-worker
    build:
      context: ./src/spring
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql