
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysql:3306/auth_me?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: example
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    active: prod
server:
  servlet:
    session:
      persistent: false
custom:
  dotnetEndpoint: "http://localhost:5000"
  azureClientId: "c4a2ab21-acdb-4a07-83be-b07b28fffe54"
  azureClientSecret: "WD57Q~88~v2Vta21TM.EqsJygrPWcPG6nbZwX"
  azureResource: "api://bc005232-4de2-4e23-a624-17f0921944de"
  azureTenant: "505fc22a-c476-49ef-97df-da53b5b7dfe9"
  azureInstance: "https://login.microsoftonline.com/"
